title: Vincent Verhoeven's blog
email: verhoevenv@gmail.com
description: >
  My opinions and insights on code, development practices,
  agile methodology and other interesting aspects of life.
baseurl: ""
url: "http://verhoevenv.github.io"
twitter_username: verhoevenv
github_username:  verhoevenv

markdown: kramdown

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
